name: Branch cutoff
description: This action performs branching and copies source branch to target branch
inputs:
  source-branch:
    required: true
    description: source branch
    default: m1
  target-branch:
    required: true
    description: target branch
    default: r1

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.source-branch }}
    - name: Create and push branch
      run: |
        if git ls-remote --heads origin ${{ inputs.target-branch }} | grep ${{ inputs.target-branch }}; then
          echo "Branch '${{ inputs.target-branch }}' already exists on remote"
          exit 1
        fi
        git checkout -b ${{ inputs.target-branch }}
        git push origin ${{ inputs.target-branch }}
      shell: bash
